import { createClient } from '@/lib/supabase/client'
import {
  Occurrence,
  CreateOccurrenceRequest,
  UpdateOccurrenceRequest,
  OccurrencesQuery,
  JsonValue,
} from '@/types/temporal'

const supabase = createClient()

async function requireUserId() {
  const {
    data: { user },
    error,
  } = await supabase.auth.getUser()

  if (error) {
    throw new Error(`Failed to load user session: ${error.message}`)
  }

  if (!user?.id) {
    throw new Error('User not authenticated')
  }

  return user.id
}

type Maybe<T> = T | null | undefined

type OccurrenceRow = {
  id: string
  user_id: string
  item_id: string
  scheduled_at: string
  title: Maybe<string>
  description: Maybe<string>
  due_at: Maybe<string>
  reminder_time: Maybe<string>
  status: Occurrence['status']
  completed_at: Maybe<string>
  is_skipped: Maybe<boolean>
  metadata: Maybe<Record<string, JsonValue>>
  created_at: string
  updated_at: string
}

const mapOccurrenceRow = (row: OccurrenceRow): Occurrence => ({
  id: row.id,
  userId: row.user_id,
  itemId: row.item_id,
  scheduledAt: row.scheduled_at,
  title: row.title ?? undefined,
  description: row.description ?? undefined,
  dueAt: row.due_at ?? undefined,
  reminderTime: row.reminder_time ?? undefined,
  status: row.status,
  completedAt: row.completed_at ?? undefined,
  isSkipped: Boolean(row.is_skipped),
  metadata: row.metadata ?? {},
  createdAt: row.created_at,
  updatedAt: row.updated_at,
})

const mapOccurrenceRows = (rows: OccurrenceRow[] | null): Occurrence[] =>
  (rows ?? []).map((row) => mapOccurrenceRow(row))

/**
 * Occurrence (recurring instance) database queries
 * Handles CRUD operations for materialized recurring instances
 */
export const occurrenceQueries = {
  /**
   * Get occurrences for the authenticated user with optional filtering
   */
  async getOccurrences(query?: OccurrencesQuery): Promise<Occurrence[]> {
    let q = supabase.from('occurrences').select('*')

    if (query?.itemId) q = q.eq('item_id', query.itemId)
    if (query?.status) q = q.eq('status', query.status)
    if (query?.scheduledBefore) q = q.lte('scheduled_at', query.scheduledBefore)
    if (query?.scheduledAfter) q = q.gte('scheduled_at', query.scheduledAfter)
    if (query?.excludeSkipped) q = q.eq('is_skipped', false)

    q = q.order('scheduled_at', { ascending: true })

    // Pagination
    if (query?.limit) {
      const offset = query.offset || 0
      q = q.range(offset, offset + query.limit - 1)
    }

    const { data, error } = await q

    if (error) throw new Error(`Failed to fetch occurrences: ${error.message}`)
    return mapOccurrenceRows(data as OccurrenceRow[] | null)
  },

  /**
   * Get a single occurrence by ID
   */
  async getOccurrence(id: string): Promise<Occurrence> {
    const { data, error } = await supabase
      .from('occurrences')
      .select('*')
      .eq('id', id)
      .single()

    if (error) throw new Error(`Failed to fetch occurrence: ${error.message}`)
    if (!data) throw new Error('Occurrence not found')
    return mapOccurrenceRow(data as OccurrenceRow)
  },

  /**
   * Get occurrences for a specific date range
   * Useful for "what's due today" queries
   */
  async getOccurrencesByDateRange(
    startDate: string,
    endDate: string,
    itemId?: string
  ): Promise<Occurrence[]> {
    let q = supabase
      .from('occurrences')
      .select('*')
      .gte('scheduled_at', startDate)
      .lte('scheduled_at', endDate)
      .eq('is_skipped', false)

    if (itemId) q = q.eq('item_id', itemId)

    const { data, error } = await q.order('scheduled_at', { ascending: true })

    if (error)
      throw new Error(`Failed to fetch occurrences: ${error.message}`)
    return mapOccurrenceRows(data as OccurrenceRow[] | null)
  },

  /**
   * Create a new occurrence
   * Usually auto-generated by triggers, but can be created manually
   */
  async createOccurrence(req: CreateOccurrenceRequest): Promise<Occurrence> {
    const userId = await requireUserId()
    const payload: Record<string, JsonValue> = {
      item_id: req.itemId,
      scheduled_at: req.scheduledAt,
      metadata: req.metadata || {},
      user_id: userId,
    }

    if (req.title !== undefined) payload.title = req.title
    if (req.description !== undefined) payload.description = req.description
    if (req.dueAt !== undefined) payload.due_at = req.dueAt
    if (req.reminderTime !== undefined)
      payload.reminder_time = req.reminderTime

    const { data, error } = await supabase
      .from('occurrences')
      .insert([payload])
      .select()
      .single()

    if (error) throw new Error(`Failed to create occurrence: ${error.message}`)
    if (!data) throw new Error('Occurrence creation failed')
    return mapOccurrenceRow(data as OccurrenceRow)
  },

  /**
   * Update an existing occurrence
   */
  async updateOccurrence(
    id: string,
    req: UpdateOccurrenceRequest
  ): Promise<Occurrence> {
    const updatePayload: Record<string, JsonValue> = {}

    if (req.title !== undefined) updatePayload.title = req.title
    if (req.description !== undefined) updatePayload.description = req.description
    if (req.dueAt !== undefined) updatePayload.due_at = req.dueAt
    if (req.reminderTime !== undefined)
      updatePayload.reminder_time = req.reminderTime
    if (req.status !== undefined) updatePayload.status = req.status
    if (req.isSkipped !== undefined) updatePayload.is_skipped = req.isSkipped
    if (req.metadata !== undefined) updatePayload.metadata = req.metadata

    // Auto-set completed_at when status changes to completed
    if (req.status === 'completed' && !updatePayload.completed_at) {
      updatePayload.completed_at = new Date().toISOString()
    }

    const { data, error } = await supabase
      .from('occurrences')
      .update(updatePayload)
      .eq('id', id)
      .select()
      .single()

    if (error) throw new Error(`Failed to update occurrence: ${error.message}`)
    if (!data) throw new Error('Occurrence not found')
    return mapOccurrenceRow(data as OccurrenceRow)
  },

  /**
   * Delete an occurrence
   */
  async deleteOccurrence(id: string): Promise<void> {
    const { error } = await supabase
      .from('occurrences')
      .delete()
      .eq('id', id)

    if (error) throw new Error(`Failed to delete occurrence: ${error.message}`)
  },

  /**
   * Mark an occurrence as completed
   */
  async completeOccurrence(id: string): Promise<Occurrence> {
    const { data, error } = await supabase
      .from('occurrences')
      .update({
        status: 'completed',
        completed_at: new Date().toISOString(),
      })
      .eq('id', id)
      .select()
      .single()

    if (error)
      throw new Error(`Failed to complete occurrence: ${error.message}`)
    if (!data) throw new Error('Occurrence not found')
    return mapOccurrenceRow(data as OccurrenceRow)
  },

  /**
   * Skip an occurrence
   * Different from delete - marks it explicitly skipped
   */
  async skipOccurrence(id: string): Promise<Occurrence> {
    const { data, error } = await supabase
      .from('occurrences')
      .update({ is_skipped: true })
      .eq('id', id)
      .select()
      .single()

    if (error) throw new Error(`Failed to skip occurrence: ${error.message}`)
    if (!data) throw new Error('Occurrence not found')
    return mapOccurrenceRow(data as OccurrenceRow)
  },
}
